name: generate_lookml

on:
  check_run:
  schedule:
    - cron: '0 9 * * WED'
    #- cron: '* * * * *'

jobs:
  content_validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.7
      uses: actions/setup-python@v1

      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install looker-sdk
        pip install PyGithub
        pip install git+https://github.com/llooker/lookml.git@f69ee32e880cada8d8e353e19a39ddfc6cdc1371
        pip install looker-sdk
        pip install lkml
        
    - name: LookML Generation
      run: |
        echo "Generating New LookML" 
        python .github/workflows/generate_lookml.py \
          --base-url https://dcloidc.dev.looker.com \
          --client-id ${{ secrets.my_client_id }} \
          --client-secret ${{ secrets.my_client_secret }} \
          --github-token ${{ secrets.GITHUB_TOKEN }} \
          --repo saraleon1/ga360 \
          --project ga_360 > generate.txt
        echo "::set-env name=GENERATE_STATS::$(cat generate.txt)" 
    - name: slack_notify
      uses: 8398a7/action-slack@v2
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} 
      with:
        status: custom
        payload: |
          {
              "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "${{ env.GENERATE_STATS }}"
                    }
                  }
                  ]
            }
 
